wandb_version: 1

batch_size:
  value: 64
data_aug:
  value: false
dense_size:
  value: 512
dropout:
  value: 0.5
freeze_option:
  value: 0
in_dims:
  value: 224
learning_rate:
  value: 0.001
n_epochs:
  value: 10
weight_decay:
  value: 0.005
