wandb_version: 1

batch_size:
  value: 128
data_aug:
  value: true
dense_size:
  value: 256
dropout:
  value: 0.5
freeze_option:
  value: 0
in_dims:
  value: 224
learning_rate:
  value: 0.0001
n_epochs:
  value: 15
weight_decay:
  value: 0.5
