_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
augmentations:
    value: false
batch_norm:
    value: true
batch_size:
    value: 32
conv_activation:
    value: mish
data_dir:
    value: /home/malavika/da6401_assignment2/inaturalist_12K/train
dense_activation:
    value: relu
dense_neurons:
    value: 256
dropout:
    value: 0
epochs:
    value: 15
filter_org:
    value: halve
kernel_size:
    value:
        - 3
        - 3
        - 5
        - 5
        - 7
lr:
    value: 0.0001
model_save_path:
    value: /home/malavika/da6401_assignment2
n_filters:
    value: 64
