wandb_version: 1

batch_size:
  value: 128
data_aug:
  value: false
dense_size:
  value: 1024
dropout:
  value: 0.2
freeze_option:
  value: 0
in_dims:
  value: 224
learning_rate:
  value: 0.001
n_epochs:
  value: 15
weight_decay:
  value: 0
